name: fluttertodo
description: "Expense Tracker App"
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.0.2
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.0
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3
  shared_preferences: ^2.2.3
  overlay_support: ^2.1.0
  awesome_notifications_fcm: ^0.9.3+1
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.4
  easy_localization: ^3.0.6

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - lib/locales/en.json
    - lib/locales/id.json
